// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for MOSH FFI API.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class MoshClientBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MoshClientBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MoshClientBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initialize the mosh library.
  /// Must be called before any other functions.
  /// Returns MOSH_OK on success.
  MoshResult mosh_init() {
    return MoshResult.fromValue(_mosh_init());
  }

  late final _mosh_initPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>(
    'mosh_init',
  );
  late final _mosh_init = _mosh_initPtr.asFunction<int Function()>();

  /// Cleanup the mosh library.
  /// Should be called when done using mosh.
  void mosh_cleanup() {
    return _mosh_cleanup();
  }

  late final _mosh_cleanupPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('mosh_cleanup');
  late final _mosh_cleanup = _mosh_cleanupPtr.asFunction<void Function()>();

  /// Create a new mosh session.
  ///
  /// @param host     The server hostname or IP
  /// @param port     The UDP port (from mosh-server)
  /// @param key      The base64 session key (from mosh-server)
  /// @param width    Initial terminal width
  /// @param height   Initial terminal height
  /// @return         Session handle or NULL on error
  MoshSession mosh_session_create(
    ffi.Pointer<ffi.Char> host,
    ffi.Pointer<ffi.Char> port,
    ffi.Pointer<ffi.Char> key,
    int width,
    int height,
  ) {
    return _mosh_session_create(host, port, key, width, height);
  }

  late final _mosh_session_createPtr =
      _lookup<
        ffi.NativeFunction<
          MoshSession Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('mosh_session_create');
  late final _mosh_session_create = _mosh_session_createPtr
      .asFunction<
        MoshSession Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
        )
      >();

  /// Set callbacks for the session.
  void mosh_session_set_callbacks(
    MoshSession session,
    MoshScreenCallback screen_cb,
    MoshErrorCallback error_cb,
    MoshStateCallback state_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mosh_session_set_callbacks(
      session,
      screen_cb,
      error_cb,
      state_cb,
      user_data,
    );
  }

  late final _mosh_session_set_callbacksPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            MoshSession,
            MoshScreenCallback,
            MoshErrorCallback,
            MoshStateCallback,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('mosh_session_set_callbacks');
  late final _mosh_session_set_callbacks = _mosh_session_set_callbacksPtr
      .asFunction<
        void Function(
          MoshSession,
          MoshScreenCallback,
          MoshErrorCallback,
          MoshStateCallback,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// Connect the session.
  /// This starts the network thread.
  /// Returns MOSH_OK on success.
  MoshResult mosh_session_connect(MoshSession session) {
    return MoshResult.fromValue(_mosh_session_connect(session));
  }

  late final _mosh_session_connectPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(MoshSession)>>(
        'mosh_session_connect',
      );
  late final _mosh_session_connect = _mosh_session_connectPtr
      .asFunction<int Function(MoshSession)>();

  /// Send user input to the session.
  ///
  /// @param session  The session handle
  /// @param data     The input data (UTF-8)
  /// @param len      Length of input data
  /// @return         MOSH_OK on success
  MoshResult mosh_session_write(
    MoshSession session,
    ffi.Pointer<ffi.Char> data,
    int len,
  ) {
    return MoshResult.fromValue(_mosh_session_write(session, data, len));
  }

  late final _mosh_session_writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(MoshSession, ffi.Pointer<ffi.Char>, ffi.Size)
        >
      >('mosh_session_write');
  late final _mosh_session_write = _mosh_session_writePtr
      .asFunction<int Function(MoshSession, ffi.Pointer<ffi.Char>, int)>();

  /// Resize the terminal.
  ///
  /// @param session  The session handle
  /// @param width    New width
  /// @param height   New height
  /// @return         MOSH_OK on success
  MoshResult mosh_session_resize(MoshSession session, int width, int height) {
    return MoshResult.fromValue(_mosh_session_resize(session, width, height));
  }

  late final _mosh_session_resizePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(MoshSession, ffi.Int, ffi.Int)>
      >('mosh_session_resize');
  late final _mosh_session_resize = _mosh_session_resizePtr
      .asFunction<int Function(MoshSession, int, int)>();

  /// Poll for updates.
  /// Should be called periodically to process network events.
  /// This will trigger callbacks if there are updates.
  ///
  /// @param session       The session handle
  /// @param timeout_ms    Timeout in milliseconds (0 for non-blocking)
  /// @return              MOSH_OK on success
  MoshResult mosh_session_poll(MoshSession session, int timeout_ms) {
    return MoshResult.fromValue(_mosh_session_poll(session, timeout_ms));
  }

  late final _mosh_session_pollPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(MoshSession, ffi.Int)>>(
        'mosh_session_poll',
      );
  late final _mosh_session_poll = _mosh_session_pollPtr
      .asFunction<int Function(MoshSession, int)>();

  /// Get current session state.
  MoshState mosh_session_get_state(MoshSession session) {
    return MoshState.fromValue(_mosh_session_get_state(session));
  }

  late final _mosh_session_get_statePtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(MoshSession)>>(
        'mosh_session_get_state',
      );
  late final _mosh_session_get_state = _mosh_session_get_statePtr
      .asFunction<int Function(MoshSession)>();

  /// Get last error message.
  /// Returns NULL if no error.
  ffi.Pointer<ffi.Char> mosh_session_get_error(MoshSession session) {
    return _mosh_session_get_error(session);
  }

  late final _mosh_session_get_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(MoshSession)>>(
        'mosh_session_get_error',
      );
  late final _mosh_session_get_error = _mosh_session_get_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(MoshSession)>();

  /// Disconnect and destroy the session.
  void mosh_session_destroy(MoshSession session) {
    return _mosh_session_destroy(session);
  }

  late final _mosh_session_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(MoshSession)>>(
        'mosh_session_destroy',
      );
  late final _mosh_session_destroy = _mosh_session_destroyPtr
      .asFunction<void Function(MoshSession)>();

  /// Get library version string.
  ffi.Pointer<ffi.Char> mosh_version() {
    return _mosh_version();
  }

  late final _mosh_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'mosh_version',
      );
  late final _mosh_version = _mosh_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

/// Session state
enum MoshState {
  MOSH_STATE_DISCONNECTED(0),
  MOSH_STATE_CONNECTING(1),
  MOSH_STATE_CONNECTED(2),
  MOSH_STATE_ERROR(3);

  final int value;
  const MoshState(this.value);

  static MoshState fromValue(int value) => switch (value) {
    0 => MOSH_STATE_DISCONNECTED,
    1 => MOSH_STATE_CONNECTING,
    2 => MOSH_STATE_CONNECTED,
    3 => MOSH_STATE_ERROR,
    _ => throw ArgumentError("Unknown value for MoshState: $value"),
  };
}

/// Result codes
enum MoshResult {
  MOSH_OK(0),
  MOSH_ERROR_INVALID_PARAMS(-1),
  MOSH_ERROR_CONNECT_FAILED(-2),
  MOSH_ERROR_NOT_CONNECTED(-3),
  MOSH_ERROR_CRYPTO(-4),
  MOSH_ERROR_NETWORK(-5),
  MOSH_ERROR_MEMORY(-6);

  final int value;
  const MoshResult(this.value);

  static MoshResult fromValue(int value) => switch (value) {
    0 => MOSH_OK,
    -1 => MOSH_ERROR_INVALID_PARAMS,
    -2 => MOSH_ERROR_CONNECT_FAILED,
    -3 => MOSH_ERROR_NOT_CONNECTED,
    -4 => MOSH_ERROR_CRYPTO,
    -5 => MOSH_ERROR_NETWORK,
    -6 => MOSH_ERROR_MEMORY,
    _ => throw ArgumentError("Unknown value for MoshResult: $value"),
  };
}

/// Screen cell - single character with attributes
final class MoshCell extends ffi.Struct {
  @ffi.Uint32()
  external int codepoint;

  @ffi.Uint32()
  external int foreground;

  @ffi.Uint32()
  external int background;

  @ffi.Uint8()
  external int bold;

  @ffi.Uint8()
  external int underline;

  @ffi.Uint8()
  external int blink;

  @ffi.Uint8()
  external int inverse;
}

/// Session handle - opaque pointer
typedef MoshSession = ffi.Pointer<ffi.Void>;

/// Screen update callback
typedef MoshScreenCallback =
    ffi.Pointer<ffi.NativeFunction<MoshScreenCallbackFunction>>;
typedef MoshScreenCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<MoshCell> cells,
      ffi.Int width,
      ffi.Int height,
      ffi.Int cursor_x,
      ffi.Int cursor_y,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef DartMoshScreenCallbackFunction =
    void Function(
      ffi.Pointer<MoshCell> cells,
      int width,
      int height,
      int cursor_x,
      int cursor_y,
      ffi.Pointer<ffi.Void> user_data,
    );

/// Error callback
typedef MoshErrorCallback =
    ffi.Pointer<ffi.NativeFunction<MoshErrorCallbackFunction>>;
typedef MoshErrorCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Char> message,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef DartMoshErrorCallbackFunction =
    void Function(
      ffi.Pointer<ffi.Char> message,
      ffi.Pointer<ffi.Void> user_data,
    );

/// State change callback
typedef MoshStateCallback =
    ffi.Pointer<ffi.NativeFunction<MoshStateCallbackFunction>>;
typedef MoshStateCallbackFunction =
    ffi.Void Function(ffi.UnsignedInt state, ffi.Pointer<ffi.Void> user_data);
typedef DartMoshStateCallbackFunction =
    void Function(MoshState state, ffi.Pointer<ffi.Void> user_data);
